#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcbform
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="practice")]
	public partial class JquerytblDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public JquerytblDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["practiceConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public JquerytblDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JquerytblDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JquerytblDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JquerytblDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<jquerytbl> jquerytbls
		{
			get
			{
				return this.GetTable<jquerytbl>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jquerytbl")]
	public partial class jquerytbl
	{
		
		private string _sno;
		
		private string _name;
		
		private string _department;
		
		public jquerytbl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sno", DbType="VarChar(10)")]
		public string sno
		{
			get
			{
				return this._sno;
			}
			set
			{
				if ((this._sno != value))
				{
					this._sno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="VarChar(20)")]
		public string department
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this._department = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
